# Week 3 Solutions for practice questions

## Numpy Practice Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [15]:
a = np.array([1,2,3])
b = np.array([2,5,6])

c=np.vstack([a,b])
d=np.hstack([a,b])
print(c)
print(d)


[[1 2 3]
 [2 5 6]]
[1 2 3 2 5 6]


 2.Find common elements between A and B.

In [1]:
import numpy as np

# Defining two arrays
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

# Finding the intersection of arrays A and B
common_elements = np.intersect1d(A, B)

print("Common elements between A and B:", common_elements)


Common elements between A and B: [3 4 5]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10.

In [2]:
import numpy as np

A = np.array([1, 4, 7, 9, 12, 5, 8])
lower_bound = 5
upper_bound = 10

# Using np.where() to find indices of numbers within the range [5, 10]
indices = np.where((A >= lower_bound) & (A <= upper_bound))

# Extracting numbers using the found indices
numbers_in_range = A[indices]

print("Numbers in range [5, 10]:", numbers_in_range)


Numbers in range [5, 10]: [7 9 5 8]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [3]:
import numpy as np

# URL of the Iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Loading the Iris dataset
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# Condition for petal length > 1.5
condition_petal_length = iris_2d[:, 2] > 1.5

# Condition for sepal length < 5.0
condition_sepal_length = iris_2d[:, 0] < 5.0

# Combining both conditions
combined_condition = condition_petal_length & condition_sepal_length

# Filtering the rows based on the combined condition
filtered_rows = iris_2d[combined_condition]

print("Filtered Rows:\n", filtered_rows)


Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Pandas Practice Questions


1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [1]:
!pip3 install pandas
import pandas as pd

# Load the DataFrame from the provided URL
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Select 'Manufacturer', 'Model', and 'Type' columns for every 20th row starting from the first row (row 0)
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

print(filtered_df)


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/f2/8c/35364a11b3e25f8e29a35420b0d18f65ec4f9d6d38e86a62d16ef998923c/pandas-2.1.1-cp39-cp39-win_amd64.whl.metadata
  Using cached pandas-2.1.1-cp39-cp39-win_amd64.whl.metadata (18 kB)
Using cached pandas-2.1.1-cp39-cp39-win_amd64.whl (10.8 MB)
   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [2]:
!pip3 install pandas
import pandas as pd

# Load the DataFrame from the provided URL
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Calculate the mean of 'Min.Price' excluding NaN values
min_price_mean = df['Min.Price'].mean()

# Replace NaN values in 'Min.Price' with its mean
df['Min.Price'].fillna(min_price_mean, inplace=True)

# Calculate the mean of 'Max.Price' excluding NaN values
max_price_mean = df['Max.Price'].mean()

# Replace NaN values in 'Max.Price' with its mean
df['Max.Price'].fillna(max_price_mean, inplace=True)

print(df[['Min.Price', 'Max.Price']])


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [ ]:
!pip3 install pandas
import pandas as pd
import numpy as np

# Creating a DataFrame with random integers between 10 and 40
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Calculating the row sum
row_sum = df.sum(axis=1)

# Filtering the rows where the sum is greater than 100
rows_greater_than_100 = df[row_sum > 100]

print("Original DataFrame:")
print(df)
print("\nRows with sum > 100:")
print(rows_greater_than_100)
